"use client";
import { useState } from "react";
import { useShop } from "./shop-store";
import { ProductArt, formatMoney } from "./product-details";
import data from "../shop-data.json";
import s from "./profile.module.css";

type Address={id:string;kind:string;city:string;area:string;building:string;apartment:string;nickname:string;directions:string;first:string;last:string;phone:string;point:{lat:number;lng:number}};
const blank:Address={id:"",kind:"Home",city:"Dubai",area:"",building:"",apartment:"",nickname:"",directions:"",first:"",last:"",phone:"",point:{lat:25.2048,lng:55.2708}};
const addressKey="barwaqt-delivery-addresses-v1";
function readAddresses():Address[]{try{const value=JSON.parse(localStorage.getItem(addressKey)||"[]");return Array.isArray(value)?value.filter(a=>a&&typeof a.id==="string"&&["city","area","building","apartment","first","last","phone"].every(k=>typeof a[k]==="string")):[];}catch{return [];}}
export function AccountAddresses(){
 const [addresses,setAddresses]=useState(readAddresses);const [draft,setDraft]=useState<Address>(blank);const [message,setMessage]=useState("");
 function store(next:Address[]){setAddresses(next);try{localStorage.setItem(addressKey,JSON.stringify(next));setMessage("Addresses saved in this browser and available at checkout.");}catch{setMessage("Browser storage is unavailable. Changes are available until you leave this screen.");}}
 return <><div className={s.panelToolbar}><p>{addresses.length} saved delivery addresses</p><button onClick={()=>{setDraft({...blank});document.getElementById("address-form")?.scrollIntoView({behavior:"smooth"});}}>＋ Add new address</button></div><div className={s.addressCards}>{addresses.map((a,i)=><article className={s.addressCard} key={a.id}><span className={s.badge}>{a.nickname||a.kind} {i===0?" · PRIMARY":""}</span><h3>{a.first} {a.last}</h3><p>+971 {a.phone}</p><div className={s.addressBlock}>{a.apartment}, {a.building}<br/>{a.area}, {a.city}</div>{a.directions&&<p>⌖ {a.directions}</p>}<div className={s.panelActions}><button onClick={()=>setDraft(a)}>Edit</button>{i>0&&<button onClick={()=>store([a,...addresses.filter(item=>item.id!==a.id)])}>Make primary</button>}<button onClick={()=>{store(addresses.filter(item=>item.id!==a.id));if(draft.id===a.id)setDraft({...blank});}}>Remove</button></div></article>)}</div><form id="address-form" className={s.card} onSubmit={e=>{e.preventDefault();const next={...draft,id:draft.id||crypto.randomUUID()};store([...addresses.filter(a=>a.id!==next.id),next]);setDraft({...blank});}}><h2>{draft.id?"Edit delivery address":"＋ Add delivery address"}</h2><div className={s.addressForm}>{([['First name','first'],['Last name','last'],['City / Emirate','city'],['Area / Street','area'],['Building','building'],['Apartment / Floor','apartment'],['Nickname (optional)','nickname'],['Delivery instructions (optional)','directions']] as const).map(([label,key])=><label className={s.field} key={key}>{label}<input aria-label={label} value={draft[key]} required={!['nickname','directions'].includes(key)} maxLength={120} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label className={s.field}>UAE mobile number<input aria-label="UAE mobile number" type="tel" required pattern="5[0-9]{8}" title="9 digits starting with 5, without +971" placeholder="501234567" maxLength={9} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value.replace(/\D/g,"")})}/></label><label className={s.field}>Address type<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{['Home','Work','Other'].map(k=><option key={k}>{k}</option>)}</select></label></div><div className={s.panelActions}><button type="button" onClick={()=>setDraft({...blank})}>Clear form</button><button className={s.save} type="submit">Save address</button></div></form><p role="status" className={s.success}>{message}</p></>;
}
const seedOrders=[{id:'BWQ-DEMO-98421',status:'In progress',product:0},{id:'BWQ-DEMO-84190',status:'Delivered',product:1},{id:'BWQ-DEMO-77312',status:'Cancelled',product:2}];
export function AccountOrders(){const {setCart}=useShop();const [orders,setOrders]=useState(seedOrders);const [tab,setTab]=useState('All orders');const [search,setSearch]=useState('');const [detail,setDetail]=useState('');const [message,setMessage]=useState('');const products=data.products.slice(0,3);return <><p className={s.demo}>Sample orders for exploring the dashboard. These are not purchases or live shipments.</p><div className={s.orderTabs}>{['All orders','In progress','Delivered','Cancelled'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t} ({orders.filter(o=>t==='All orders'||o.status===t).length})</button>)}</div><input className={s.orderSearch} aria-label="Search orders" placeholder="Search by order ID or product name…" value={search} onChange={e=>setSearch(e.target.value)}/>{orders.filter(o=>(tab==='All orders'||o.status===tab)&&`${o.id} ${products[o.product].name}`.toLowerCase().includes(search.toLowerCase())).map(o=>{const p=products[o.product];return <article className={s.orderCard} key={o.id}><div className={s.panelToolbar}><div><h2>#{o.id}</h2><span className={s.badge}>{o.status.toUpperCase()} · DEMO</span></div><small>Sample order · AED {formatMoney(p.price)}</small></div>{o.status==='In progress'&&<ol className={s.orderTimeline}>{['Placed','Confirmed','Packed','Dispatched','Delivered'].map((step,i)=><li key={step} data-done={i<4}><span>{i<4?'✓':'⌂'}</span>{step}</li>)}</ol>}<div className={s.orderProduct}><ProductArt src={p.image} alt={p.name}/><div><h3>{p.name}</h3><p>Quantity: 1</p></div><strong>AED {formatMoney(p.price)}</strong></div><div className={s.panelActions}>{o.status==='In progress'&&<button onClick={()=>{setOrders(orders.map(item=>item.id===o.id?{...item,status:'Cancelled'}:item));setMessage('Sample order cancelled. No payment or refund was processed.');}}>Cancel demo order</button>}<button onClick={()=>setDetail(detail===o.id?'':o.id)}> {detail===o.id?'Hide details':'View details / invoice'}</button>{o.status==='In progress'?<button className={s.save} onClick={()=>{setDetail(o.id);setMessage('Tracking preview: the sample order is dispatched. Live rider tracking is not connected.');}}>Track order</button>:<button className={s.save} onClick={()=>{setCart(prev=>({...prev,[p.id]:Math.min(99,(prev[p.id]||0)+1)}));setMessage(`${p.name} added to your cart.`);}}>Buy again</button>}</div>{detail===o.id&&<div className={s.invoice}><h3>Order details · {o.id}</h3><p>{o.status} · Quantity 1 · AED {formatMoney(p.price)}</p><p>This sample invoice is a preview, not a tax invoice. No payment has been collected.</p><button onClick={()=>window.print()}>Print preview</button></div>}</article>})}<p role="status" className={s.success}>{message}</p>{!orders.some(o=>(tab==='All orders'||o.status===tab)&&`${o.id} ${products[o.product].name}`.toLowerCase().includes(search.toLowerCase()))&&<div className={s.card}>No matching orders.</div>}</>;}
export function AccountPayments(){const [selected,setSelected]=useState('Cash on Delivery');return <><p className={s.demo}>Choose a preference for this preview. No financial accounts are linked or card details stored.</p>{['JazzCash','Easypaisa','Card','Cash on Delivery'].map((name,i)=><article className={s.paymentCard} key={name}><span className={s.paymentMark}>{['JC','EP','▤','₨'][i]}</span><div><h3>{name}</h3><p>{name===selected?'Selected preference':'Available during checkout'}</p></div><button aria-pressed={selected===name} onClick={()=>setSelected(name)}>{name===selected?'Selected':'Set preference'}</button></article>)}<p className={s.success} role="status">{selected} selected for this preview.</p></>;}
