"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import data from "../shop-data.json";
import { categories, categoryHref } from "../categories";
import { useShop } from "./shop-store";
import { ShopHeader, ShopFooter } from "./shop-shell";
import s from "./category.module.css";

type Category = typeof categories[number];
const money=(n:number)=>n.toLocaleString("en-AE",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function CategoryListing({category}:{category:Category}) {
 const {cart,setCart,saved,setSaved}=useShop();
 const [brands,setBrands]=useState<string[]>([]);
 const [min,setMin]=useState("");const [max,setMax]=useState("");
 const [rating,setRating]=useState(0);const [deals,setDeals]=useState(false);
 const [fulfillment,setFulfillment]=useState<string[]>([]);
 const [sort,setSort]=useState("recommended");const [query,setQuery]=useState("");
 const [brandQuery,setBrandQuery]=useState("");const [limit,setLimit]=useState(25);
 const [view,setView]=useState<"grid"|"list">("grid");
 const [filtersOpen,setFiltersOpen]=useState(false);const [notice,setNotice]=useState("");
 const products=category.productIds.map(id=>data.products.find(p=>p.id===id)).filter((p):p is typeof data.products[number]=>!!p).map((p,index)=>({...p,brand:p.id.startsWith("category-")?"Barwaqt":p.name.split(" ")[0],fulfillment:index%3===0?"supermall":"express"}));
 const brandOptions=Array.from(new Set(products.map(p=>p.brand))).sort();
 const children=categories.filter(c=>c.parent===category.slug);
 const parent=categories.find(c=>c.slug===category.parent);
 const siblings=categories.filter(c=>c.parent===(category.parent||category.slug));
 const coffee=category.slug.includes("coffee")||category.slug==="grocery"||category.slug==="grocery-beverages";
 const filtered=products.filter(p=>(!brands.length||brands.includes(p.brand))&&(!min||p.price>=Number(min))&&(!max||p.price<=Number(max))&&p.rating>=rating&&(!deals||(p.old-p.price)/p.old>=.2)&&(!fulfillment.length||fulfillment.includes(p.fulfillment))&&p.name.toLowerCase().includes(query.toLowerCase()));
 filtered.sort((a,b)=>sort==="price-low"?a.price-b.price:sort==="price-high"?b.price-a.price:sort==="rating"?b.rating-a.rating:sort==="discount"?(b.old-b.price)/b.old-(a.old-a.price)/a.old:0);
 const activeCount=brands.length+fulfillment.length+(min?1:0)+(max?1:0)+(rating?1:0)+(deals?1:0);
 function reset(){setBrands([]);setMin("");setMax("");setRating(0);setDeals(false);setFulfillment([]);setQuery("");setLimit(25);}
 function toggle(value:string,list:string[],set:(value:string[])=>void){set(list.includes(value)?list.filter(v=>v!==value):[...list,value]);setLimit(25);}
 return <><ShopHeader/><main className={s.page}><nav className={s.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span>{parent&&<><Link href={categoryHref(parent.title)}>{parent.title}</Link><span>›</span></>}<span>{category.title}</span></nav><header className={s.categoryHeading}><h1>{category.title}<span>{products.length} ITEMS</span></h1><p>Discover everyday favourites, trusted essentials, and more for your home and lifestyle.</p></header>{children.length>0&&<nav className={s.categoryTiles} aria-label="Subcategories">{children.map(c=><Link key={c.slug} href={`/category/${c.slug}`}>{c.title}<small>{c.productIds.length} products</small></Link>)}</nav>}<section className={s.featureBanner} aria-label={`${category.title} collection`}><div className={s.featureCopy}><span className={s.featureBadge}>THE BARWAQT COLLECTION</span><h2>{category.title=== "Home & kitchen"?"Everyday essentials. Extraordinary possibilities.":`Find your favourites in ${category.title.toLowerCase()}`}</h2><p>Explore our collection and discover something for every day.</p><a href="#category-results">Explore the collection →</a></div><div className={s.featureImage}>{coffee?<Image src="/category/coffee-banner.webp" alt="Discover coffee favourites" width={1401} height={213} loading="eager" unoptimized/>:category.image?<Image src={category.image} alt={category.title} width={500} height={400} loading="eager" unoptimized/>:<span>{category.title}</span>}</div><div className={s.featureFooter}><strong>BARWAQT</strong><span>Your everyday essentials, all in one place</span><a href="#category-results">Shop the collection →</a></div></section><div className={s.layout} id="category-results">
 <aside className={`${s.sidebar} ${filtersOpen?s.sidebarOpen:""}`} aria-label="Product filters"><div className={s.filterHeading}><h2>Filters {activeCount>0&&`(${activeCount})`}</h2><button onClick={reset}>Clear all</button><button className={s.closeFilters} onClick={()=>setFiltersOpen(false)} aria-label="Close filters">×</button></div><details open><summary>Fulfilled by</summary>{["supermall","express"].map(type=><label className={s.check} key={type}><input type="checkbox" checked={fulfillment.includes(type)} onChange={()=>toggle(type,fulfillment,setFulfillment)}/><div><span className={type==="express"?s.express:s.supermall}>{type}</span><small>{type==="express"?"Everyday delivery":"Fast delivery"}</small></div></label>)}</details><details open><summary>Category</summary><Link className={s.categoryLink} href={parent?categoryHref(parent.title):categoryHref("All products")}>‹ {parent?.title||"All categories"}</Link><b className={s.currentCategory}>{category.title}</b>{(children.length?children:siblings).slice(0,10).map(c=><Link className={s.categoryLink} key={c.slug} href={`/category/${c.slug}`}>{c.title}</Link>)}</details><details open><summary>Brand</summary><input className={s.brandSearch} aria-label="Search brands" placeholder="Search brands" value={brandQuery} onChange={e=>setBrandQuery(e.target.value)}/><div className={s.brandOptions}>{brandOptions.filter(b=>b.toLowerCase().includes(brandQuery.toLowerCase())).map(brand=><label className={s.check} key={brand}><input type="checkbox" checked={brands.includes(brand)} onChange={()=>toggle(brand,brands,setBrands)}/><span>{brand}</span><small>{products.filter(p=>p.brand===brand).length}</small></label>)}</div></details><details open><summary>Price (AED)</summary><div className={s.priceInputs}><label>Min<input type="number" min="0" aria-label="Minimum price" placeholder="0" value={min} onChange={e=>{setMin(e.target.value);setLimit(25);}}/></label><span>–</span><label>Max<input type="number" min="0" aria-label="Maximum price" placeholder="Any" value={max} onChange={e=>{setMax(e.target.value);setLimit(25);}}/></label></div>{min&&max&&Number(min)>Number(max)&&<p className={s.filterError}>Maximum must be greater than minimum.</p>}</details><details open><summary>Deals</summary><label className={s.check}><input type="checkbox" checked={deals} onChange={e=>{setDeals(e.target.checked);setLimit(25);}}/>20% off or more</label></details><details open><summary>Product Rating</summary>{[0,4,4.5].map(value=><label className={s.check} key={value}><input type="radio" name="rating" checked={rating===value} onChange={()=>{setRating(value);setLimit(25);}}/><span>{value?`${value} ★ & above`:"All ratings"}</span></label>)}</details><button className={s.applyMobile} onClick={()=>setFiltersOpen(false)}>SHOW {filtered.length} RESULTS</button></aside>
 <section className={s.listing}><div className={s.toolbar}><h2>{filtered.length} results for <strong>“{category.title}”</strong></h2><label>Sort by:<select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Barwaqt Recommended</option><option value="price-low">Price: Low to high</option><option value="price-high">Price: High to low</option><option value="rating">Top rated</option><option value="discount">Biggest discount</option></select></label><div className={s.viewToggle} aria-label="Product view"><button aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>setView("grid")}>▦</button><button aria-label="List view" aria-pressed={view==="list"} onClick={()=>setView("list")}>☰</button></div></div><div className={s.controls}><button className={s.filterToggle} onClick={()=>setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}>☷ Filters {activeCount?`(${activeCount})`:""}</button><input type="search" aria-label="Search this category" placeholder={`Search ${category.title.toLowerCase()}…`} value={query} onChange={e=>{setQuery(e.target.value);setLimit(25);}}/><button className={deals?s.selectedChip:""} aria-pressed={deals} onClick={()=>{setDeals(!deals);setLimit(25);}}>◈ Deals</button><button className={max==="100"?s.selectedChip:""} aria-pressed={max==="100"} onClick={()=>{setMax(max==="100"?"":"100");setLimit(25);}}>Under AED 100</button>{coffee&&<Link href={categoryHref("Coffee","Grocery")}>Coffee ›</Link>}</div>{activeCount>0&&<div className={s.activeFilters}><span>{activeCount} active filters</span>{brands.map(b=><button key={b} onClick={()=>toggle(b,brands,setBrands)}>{b} ×</button>)}<button onClick={reset}>Clear all filters</button></div>}
 {filtered.length?<><div className={`${s.products} ${view==="list"?s.listView:""}`}>{filtered.slice(0,limit).map((p,index)=><article key={p.id} className={s.product} data-price={p.price}><div className={s.art}>{index%5===0&&<span className={s.best}>Best Seller</span>}<button className={`${s.heart} ${saved.includes(p.id)?s.saved:""}`} aria-label={`${saved.includes(p.id)?"Unsave":"Save"} ${p.name}`} aria-pressed={saved.includes(p.id)} onClick={()=>setSaved(previous=>previous.includes(p.id)?previous.filter(id=>id!==p.id):[...previous,p.id])}>♡</button><Link href={`/product/${p.id}`} aria-label={`View ${p.name}`}><Image src={p.image} alt={p.name} width={260} height={320} unoptimized loading={index<5?"eager":"lazy"}/></Link></div><div className={s.productBody}><span className={s.productBrand}>{p.brand}</span><Link className={s.productName} href={`/product/${p.id}`}>{p.name}</Link><p className={s.rating}>★ <b>{p.rating.toFixed(1)}</b></p><p className={s.price}><small>AED</small> <strong>{money(p.price)}</strong></p><p className={s.discount}><del>{money(p.old)}</del> <span>{Math.round((1-p.price/p.old)*100)}% OFF</span></p><p className={s.shipping}>♧ Free delivery</p><span className={s.offer}>Extra savings on selected items</span><div className={s.fulfilled}><span className={p.fulfillment==="express"?s.express:s.supermall}>{p.fulfillment}</span><small>{p.fulfillment==="express"?"Tomorrow":"Fast delivery"}</small></div><button className={s.add} disabled={(cart[p.id]||0)>=99} aria-label={`Add ${p.name} to cart`} onClick={()=>{setCart(previous=>({...previous,[p.id]:(previous[p.id]||0)+1}));setNotice(`${p.name} added to cart`);}}>＋ Add to cart</button></div></article>)}</div><div className={s.loadMore}><p>Showing {Math.min(limit,filtered.length)} of {filtered.length} products</p>{limit<filtered.length&&<button onClick={()=>setLimit(previous=>previous+25)}>LOAD MORE PRODUCTS</button>}</div></>:<div className={s.empty}><span>⌕</span><h2>{products.length?"No products match your filters":"This collection is coming soon"}</h2><p>{products.length?"Try another brand, a wider price range, or clear your filters.":"Explore our other categories while we add products to this collection."}</p>{products.length?<button onClick={reset}>Clear filters</button>:<Link href={categoryHref("All products")}>Browse all products</Link>}</div>}
 {coffee&&filtered.length>10&&<div className={s.bottomBanner}><Image src="/category/coffee-banner-secondary.webp" alt="Italy in every cup — explore coffee favourites" width={1401} height={210} unoptimized/></div>}<p className={s.demo}>Demo catalog. Products, prices, ratings, and delivery labels are sample data.</p></section></div></main><ShopFooter/>{notice&&<div className={s.toast} role="status"><span>{notice}</span><Link href="/checkout">View cart</Link><button onClick={()=>setNotice("")} aria-label="Dismiss notification">×</button></div>}</>;
}
