"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import data from "../shop-data.json";
import { useShop } from "./shop-store";
import { ShopHeader, ShopFooter } from "./shop-shell";
import { ProductArt, Recommendations, formatMoney } from "./product-details";
import c from "../commerce.module.css";
import DeliveryFlow from "./delivery-flow";
import delivery from "./delivery.module.css";
export default function Checkout(){
 const {cart,setCart}=useShop();
 const [code,setCode]=useState("");
 const [coupon,setCoupon]=useState(false);
 const [couponMessage,setCouponMessage]=useState("");
 const [deliveryOpen,setDeliveryOpen]=useState(false);
 const modal=useRef<HTMLDialogElement>(null);
 const items=data.products.filter(p=>cart[p.id]>0);
 const count=items.reduce((sum,p)=>sum+cart[p.id],0);
 const subtotal=items.reduce((sum,p)=>sum+p.price*cart[p.id],0);
 const discount=coupon?Math.min(subtotal*.1,50):0;
 const service=items.length?3.49:0;
 const total=subtotal-discount+service;
 function openCheckout(){setDeliveryOpen(true);modal.current?.showModal();}
 function closeDelivery(){modal.current?.close();setDeliveryOpen(false);}
 function remove(id:string){setCart(previous=>{const next={...previous};delete next[id];return next;});}
 return <><ShopHeader/><main className={c.checkoutPage}><div className={c.savingsBanner}><b>noon <span>one</span></b><strong>A little more value. Every day.</strong><span>Discover offers for your basket</span></div>{items.length===0?<section className={c.emptyCart}><span>♧</span><h1>Your cart is empty</h1><p>Find something you love and add it to your basket.</p><Link className={c.blueButton} href="/">Start shopping</Link><Link href="/product/nescafe-gold-190g">Explore Nescafe Gold Instant Coffee →</Link></section>:<div className={c.checkoutGrid}><div><h1 className={c.cartTitle}>Your cart <span>({count} {count===1?"item":"items"})</span></h1><section className={c.cartList} aria-label="Cart items"><div className={c.mallHeader}><span className={c.supermall}>supermall</span></div>{items.map(p=><article className={c.cartProduct} key={p.id}><div className={c.cartImage}><Link href={`/product/${p.id}`}><ProductArt src={p.image} alt={p.name}/></Link><div className={c.quantityControls}><button aria-label={`Decrease quantity of ${p.name}`} onClick={()=>setCart(previous=>({...previous,[p.id]:Math.max(0,previous[p.id]-1)}))}>−</button><span aria-label="Quantity">{cart[p.id]}</span><button disabled={cart[p.id]>=99} aria-label={`Increase quantity of ${p.name}`} onClick={()=>setCart(previous=>({...previous,[p.id]:previous[p.id]+1}))}>+</button></div></div><div className={c.cartProductInfo}><div className={c.cartProductHeading}><Link href={`/product/${p.id}`}>{p.name}</Link><b>AED {formatMoney(p.price*cart[p.id])}</b><button className={c.removeButton} onClick={()=>remove(p.id)} aria-label={`Remove ${p.name}`}>×</button></div><p className={c.cartVariant}>{p.id.startsWith("nescafe")?`Size: ${p.id.endsWith("190g")?"190 grams":"47.5 grams"}`:"Standard selection"}</p><p className={c.deliveryText}>ϟ Express delivery available</p><div className={c.cartOffers}><span>Extra 10% off</span><span>Great everyday value</span></div><p className={c.small}>♨ Selling out fast</p><p className={c.cartMeta}>♧ Free shipping　 ◇ {p.group===6?"Non-returnable":"Seller return policy applies"}　 ▧ Sold by noon</p></div></article>)}<div className={c.cartNote}>◷ Need it later? Select a delivery preference at checkout.</div><div className={c.cartNote}><span className={c.express}>one</span> More everyday value with noon.</div></section><section className={c.recommendBox}><h2>Recommended for you</h2><Recommendations products={data.products.filter(p=>!cart[p.id]&&[4,6].includes(p.group)).slice(0,5)}/></section></div>
 <aside className={c.summaryColumn}><section className={c.summary}><h2>Order Summary <span>{count} items</span></h2><dl><div><dt>Subtotal</dt><dd>AED {formatMoney(subtotal)}</dd></div><div><dt>supermall Shipping Fee</dt><dd className={c.green}>FREE</dd></div><div><dt><abbr title="A flat fee applied to this demo basket">supermall Service Fee</abbr></dt><dd>AED {formatMoney(service)}</dd></div>{coupon&&<div><dt>WELCOME10 discount</dt><dd className={c.green}>− AED {formatMoney(discount)}</dd></div>}<div className={c.summaryTotal}><dt>Total</dt><dd>AED {formatMoney(total)}</dd></div></dl></section><button className={c.checkoutButton} onClick={openCheckout}>Checkout</button><section className={c.couponBox}><h2>Got a coupon?</h2><form onSubmit={e=>{e.preventDefault();const valid=code.trim().toUpperCase()==="WELCOME10";setCoupon(valid);setCouponMessage(valid?"WELCOME10 applied: 10% off, up to AED 50.":"This code is not valid. Try WELCOME10.");}}><input aria-label="Coupon code" placeholder="Coupon Code" value={code} onChange={e=>setCode(e.target.value)}/><button type="submit">APPLY</button></form><p className={coupon?c.green:c.small} role="status">{couponMessage}</p><details><summary>⊕ View Available Offers</summary><p>Use <b>WELCOME10</b> for 10% off your items, up to AED 50. One coupon per basket.</p></details></section><section className={c.benefits}><h2>Savings and Benefits</h2><div className={c.benefitGrid}><div><strong>Free</strong><p>Shipping on your basket</p></div><div><strong>10% off</strong><p>With WELCOME10</p></div><div><strong>Express</strong><p>Delivery options</p></div></div><p className={c.benefitFoot}>Your favourites, delivered your way.</p></section><p className={c.demoNote}>Demo checkout. No payment is collected and no real order is placed.</p></aside></div>}</main><ShopFooter/>
 <dialog aria-label="Delivery address and checkout" ref={modal} className={delivery.dialog} onCancel={()=>setDeliveryOpen(false)} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDelivery();}}}>{deliveryOpen&&<DeliveryFlow count={count} total={total} onClose={closeDelivery}/>}</dialog></>;
}
