import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import data from "../shop-data.json";
import { categoryHref } from "../categories";
import { BrandLogo } from "./brand";
import s from "./home-sections.module.css";
type Product=typeof data.products[number];
const departments=[['Grocery','♧'],['Electronics','▣'],['Mobiles','▯'],['Women’s fashion','♙'],['Home & kitchen','⌂'],['Beauty','✿'],['Health & nutrition','♡'],['Baby','♧'],['Sports & outdoors','⚑'],['Automotive','▱'],['Toys','✦'],['Watches','◷']];
const rows:[string,string,string,number][]=[['Best Sellers','Discover favourites across our collections','Electronics',1],['Top Deals in Home & Living','Upgrade your everyday with thoughtful essentials','Home & kitchen',13],['Beauty & Fragrances','Everyday beauty, exceptional finds','Beauty',12],['Grocery Deals & Daily Staples','Stock up on everyday favourites','Grocery',6],['More Grocery Favourites','A little inspiration for your everyday basket','Grocery',20],['Fashion for Men','Explore the latest styles, shoes and accessories','Men’s fashion',11],['Fashion for Women','Discover everyday looks and special favourites','Women’s fashion',10],['Kids & Baby Essentials','Little essentials for your growing family','Baby',23],['Sports & Outdoors','Get moving with everyday fitness essentials','Sports & outdoors',27],['Automotive & Hardware Tools','Care for your vehicle, home and next project','Automotive',28]];
function Art({src,alt,eager=false}:{src:string;alt:string;eager?:boolean}){return <Image src={src} alt={alt} width={800} height={500} loading={eager?"eager":"lazy"} unoptimized/>;}
export function HomeSections({card}:{card:(p:Product)=>ReactNode}){
 const pick=(group:number)=>data.products.filter(p=>p.group===group).slice(0,6);
 return <div className={s.home}><section className={s.hero}><div className={s.heroMain}><Art src="/shop/hero.webp" alt="Featured GoPro collection" eager/><div className={s.heroCopy}><span>FRESH FINDS · EVERY DAY</span><h1>Your Favourite Finds,<br/><em>Right on Time.</em></h1><p>Discover electronics, fashion and everyday essentials, all in one place.</p><Link href={categoryHref('Deals')}>Shop favourites →</Link><div className={s.dots}><b/><i/><i/><i/></div></div></div><div className={s.tech}><span>FEATURED TECH</span><h2>Latest Electronics & Gadgets</h2><p>Explore your next everyday upgrade.</p><Link href={categoryHref('Electronics')}>Shop now ›</Link><Art src="/shop/reason-2.webp" alt="Explore the latest electronics" eager/></div></section>
 <section className={s.section}><header><h2>Explore Top Categories</h2><Link href={categoryHref('All products')}>View all →</Link></header><div className={s.categories}>{departments.map(([name,icon],i)=><Link key={name} href={categoryHref(name)}><span style={{background:['#fff2e8','#edf9ec','#eef3ff','#fff0f6'][i%4],color:['#d57c20','#098a42','#4f68d9','#b84482'][i%4]}}>{icon}</span>{name}</Link>)}</div></section>
 <section className={s.section}><header><div><h2>Top Picks Near You <small>Everyday favourites</small></h2><p>Discover something for your home, your style, and your day.</p></div><Link href={categoryHref('Deals')}>View all →</Link></header><div className={s.featured}>{[['Grocery','Top deals, wide selection'],['Bestsellers','Shop our top picks'],['New arrivals','The latest finds'],['Everyday essentials','Something for every day']].map(([name,desc],i)=><Link key={name} href={categoryHref(i===0?'Grocery':i===2?'Electronics':'All products')}><Art src={`/shop/reason-${i}.webp`} alt={name}/><h3>{name}</h3><p>{desc}</p><span>Explore collection →</span></Link>)}<div className={s.promo}><small>SPECIAL PROMO</small><h3>Everyday<br/>Deals</h3><p>Your favourites, with more to discover.</p><Link href={categoryHref('Deals')}>Shop deals ›</Link></div><div className={`${s.promo} ${s.lime}`}><small>DAILY ESSENTIALS</small><h3>Grocery<br/>Essentials</h3><p>Fill your basket with everyday favourites.</p><Link href={categoryHref('Grocery')}>Shop grocery ›</Link></div></div></section>
 <section className={s.flash}><header><div><h2>ϟ Mega Flash Deals</h2><p>Featured savings from across our collections</p></div><Link href={categoryHref('Deals')}>Shop all deals →</Link></header><div className={s.products}>{[...pick(-1),...pick(2)].slice(0,6).map(card)}</div></section>
 <section className={s.banners}>{[['New Arrivals','Discover your next favourite','/shop/hero.webp','Electronics'],['Fashion Trends','Style for every day','/shop/fashion.webp','Women’s fashion'],['Home & Living','Make your space your own','/shop/category-11-0.webp','Home & kitchen']].map(([title,desc,img,category])=><Link href={categoryHref(category)} key={title}><Art src={img} alt={title}/><div><small>{desc}</small><h2>{title}</h2><span>Shop now →</span></div></Link>)}</section>
 <section className={s.popular}><header><h2>Popular Categories</h2><Link href={categoryHref('All products')}>View all →</Link></header><div>{['Mobiles','Laptops','Men’s fashion','Women’s fashion','Home & kitchen','Beauty'].map(name=><Link href={categoryHref(name)} key={name}><span>▦</span>{name}</Link>)}</div></section>
 <div id="products">{rows.map(([title,description,category,group])=><section className={s.section} key={title}><header><div><h2>{title}</h2><p>{description}</p></div><Link href={categoryHref(category)}>View all →</Link></header><div className={s.products}>{pick(group).map(card)}</div></section>)}</div>
 <section className={s.more}><header><h2>More Categories to Explore</h2><Link href={categoryHref('All products')}>View all →</Link></header><div>{['Health & nutrition','Baby','Toys','Eyewear','Watches','Stationery & office supplies','Furniture','Home appliances'].map((name,i)=><Link href={categoryHref(name)} key={name}><span>{['♡','♧','✦','◉','◷','▤','⌂','▣'][i]}</span>{name}</Link>)}</div></section>
 <section className={s.upgrade}><Art src="/shop/hero.webp" alt="Explore the technology collection"/><div><span>PERFORMANCE REDEFINED</span><h2>UPGRADE YOUR TECH STACK</h2><p>Explore cameras, electronics and everyday technology.</p><Link href={categoryHref('Electronics')}>Shop hardware →</Link></div></section>
 <section className={s.benefits}>{[['♧','Delivery options','Choose at checkout'],['▣','Easy shopping','All your favourites together'],['✦','Everyday finds','Explore our collections'],['♡','Save favourites','Keep your personal wishlist'],['↗','Shop your way','At home or on the go']].map(([icon,title,desc])=><div key={title}><span>{icon}</span><div><b>{title}</b><p>{desc}</p></div></div>)}</section>
 <section className={s.searches}><h2>Popular Searches</h2><div>{Array.from(new Set([...data.categories.flatMap(c=>[c.title,...c.labels]),...data.products.filter(p=>p.group>=0&&p.group<7).map(p=>p.name)])).map(name=><Link key={name} href={`/?q=${encodeURIComponent(name)}`}>{name}</Link>)}</div></section></div>;
}
export function HomeFooter(){return <footer className={s.footer}><div className={s.footerGrid}><Link href="/" aria-label="Barwaqt home"><BrandLogo/></Link>{[['SHOP DEPARTMENTS','Electronics','Grocery','Home & kitchen','Beauty','Women’s fashion'],['CUSTOMER SERVICE','My account','Wishlist','Shopping cart'],['ABOUT BARWAQT','Discover our collections','Everyday essentials'],['MY ACCOUNT','Profile','Saved items','Cart']].map(([title,...links])=><div key={title}><h3>{title}</h3>{links.map(label=><Link key={label} href={['My account','Profile'].includes(label)?'/profile':['Wishlist','Saved items'].includes(label)?'/wishlist':['Cart','Shopping cart'].includes(label)?'/checkout':categoryHref(label)}>{label}</Link>)}</div>)}<div><h3>SHOP ANYTIME</h3><p>Your favourites, right on time.</p><Link className={s.footerCta} href={categoryHref('All products')}>Explore Barwaqt →</Link></div></div><div className={s.copyright}><span>© 2026 Barwaqt. All rights reserved.</span><span>Visa · Mastercard · Cash on delivery</span></div></footer>;}
