"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { categoryHref } from "../categories";
import { useEffect, useRef, useState } from "react";
import data from "../shop-data.json";
import { useShop } from "./shop-store";
import { ShopHeader, ShopFooter } from "./shop-shell";
import c from "../commerce.module.css";
import ProductSections from "./product-sections";
type Product = typeof data.products[number];
export const formatMoney = (n: number) => n.toLocaleString("en-AE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export function ProductArt({src,alt,className,eager=false}:{src:string;alt:string;className?:string;eager?:boolean}){return <Image src={src} alt={alt} width={500} height={600} unoptimized loading={eager?"eager":"lazy"} className={className}/>}
export function Recommendations({products}:{products:Product[]}) {return <div className={c.recommendations}>{products.map(p=><Link href={`/product/${p.id}`} key={p.id} className={c.recommendation}><ProductArt src={p.image} alt={p.name}/><p>{p.name}</p><small className={c.green}>★ {p.rating}</small><strong>AED {formatMoney(p.price)}</strong><span className={c.express}>express</span></Link>)}</div>}
export default function ProductDetails({product}:{product:Product}) {
 const {cart,setCart,saved,setSaved}=useShop();
 const router=useRouter();
 const zoom=useRef<HTMLDialogElement>(null);
 const coffee=product.id.startsWith("nescafe");
 const [imageIndex,setImageIndex]=useState(0);
 const [delivery,setDelivery]=useState("express");
 const [quantity,setQuantity]=useState(1);
 const [message,setMessage]=useState("");
 const [bundle,setBundle]=useState<string[]>([product.id]);
 const drawer=useRef<HTMLDialogElement>(null);
 // Cached routes can hide a page without removing its native modal from the top layer.
 useEffect(() => {
  const element = drawer.current;
  const zoomElement=zoom.current;
  return () => {element?.close();zoomElement?.close();};
 }, []);
 const gallery=coffee?[product.image,"/product/coffee-label.webp","/product/coffee-jar.webp"]:[product.image];
 const related=data.products.filter(p=>p.id!==product.id&&(coffee?p.group===6:p.group===product.group)).slice(0,6);
 const bundleProducts=[product,...related.slice(0,2)];
 function add(ids: string[] = [product.id]) {setCart(previous=>{const next={...previous};ids.forEach(id=>next[id]=(next[id]||0)+(id===product.id?quantity:1));return next;});drawer.current?.showModal();}
 function buyNow(){setCart(previous=>({...previous,[product.id]:Math.min(99,(previous[product.id]||0)+quantity)}));router.push("/checkout");}
 async function copyCoupon(){try{await navigator.clipboard.writeText("WELCOME10");setMessage("WELCOME10 copied. Apply it at checkout for 10% off, up to AED 50.");}catch{setMessage("Use code WELCOME10 at checkout for 10% off, up to AED 50.");}}
 const count=Object.values(cart).reduce((a,b)=>a+b,0);
 return <><ShopHeader/><main className={c.productPage}><nav className={c.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href={categoryHref(coffee?"Grocery":"All products")}>{coffee?"Grocery":"Shop"}</Link><span>›</span><span>{coffee?"Beverages　›　Coffee　›　Instant Coffee":product.section}</span></nav>
 <div className={c.productGrid}><section className={c.gallery} aria-label="Product images"><div className={c.thumbnails}>{gallery.map((src,i)=><button key={src+i} className={imageIndex===i?c.activeThumb:""} onClick={()=>setImageIndex(i)} aria-label={`View image ${i+1}`} aria-pressed={imageIndex===i}><ProductArt src={src} alt=""/></button>)}</div><div className={c.mainImage}><button className={c.heart} aria-label={saved.includes(product.id)?"Remove from wishlist":"Save to wishlist"} aria-pressed={saved.includes(product.id)} onClick={()=>setSaved(previous=>previous.includes(product.id)?previous.filter(id=>id!==product.id):[...previous,product.id])}>{saved.includes(product.id)?"♥":"♡"}</button><ProductArt src={gallery[imageIndex]} alt={product.name} eager/><button className={c.zoomButton} onClick={()=>zoom.current?.showModal()}>⌕ View larger</button><span className={c.galleryBadge}>BARWAQT COLLECTION</span></div></section>
 <section className={c.productInfo}><Link className={c.brand} href={categoryHref(coffee?"Grocery":"All products")}>{coffee?"Nescafe":product.name.split(" ")[0]} ›</Link><h1>{coffee?"Gold Instant Coffee "+(product.id.endsWith("190g")?"190grams":"47.5grams"):product.name}</h1><button className={c.ratingLink} onClick={()=>{document.getElementById("product-reviews")?.scrollIntoView({behavior:"smooth"});}}>{product.rating} <span>★★★★★</span> <u>Ratings & reviews</u></button><div className={c.pricePanel}><div className={c.priceRow}><p className={c.productPrice}>AED {formatMoney(product.price)}</p><del>AED {formatMoney(product.old)}</del><span>{Math.round((1-product.price/product.old)*100)}% OFF</span></div><p className={c.small}>Delivery availability and basket total are confirmed at checkout.</p><div className={c.couponCard}><span>◇</span><div><b>Coupon: <strong>WELCOME10</strong></b><p>10% off your items, up to AED 50</p></div><button onClick={copyCoupon}>COPY CODE</button></div><p role="status" className={c.small}>{message}</p></div>{coffee&&<p className={c.muted}>{product.id.endsWith("190g")?"190 g":"47.5 g"} · Rich aroma & smooth taste</p>}<details className={c.offer}><summary>✿ Best price with available offers</summary><p>Use WELCOME10 at checkout for 10% off your items, up to AED 50.</p></details><Link className={c.bestLink} href={categoryHref(coffee?"Grocery":"All products")}>✦ Explore other bestsellers in {coffee?"Instant Coffee":"this category"} ›</Link>
 <div className={c.infoBlock}><p className={c.eyebrow}>DELIVERY INFORMATION</p><label className={c.deliveryOption}><input type="radio" name="delivery" value="express" checked={delivery==="express"} onChange={()=>setDelivery("express")}/><span className={c.supermall}>supermall</span><span>Get it <b>today</b></span></label><span className={c.or}>or</span><label className={c.deliveryOption}><input type="radio" name="delivery" value="tomorrow" checked={delivery==="tomorrow"} onChange={()=>setDelivery("tomorrow")}/><span className={c.express}>express</span><span>Get it <b>tomorrow</b></span></label><p className={c.small}>Delivery availability is confirmed with your address at checkout.</p></div>
 {coffee&&<div className={c.infoBlock}><p className={c.eyebrow}>SIZE</p><div className={c.sizes}>{[["nescafe-gold-190g","190 grams"],["nescafe-gold-47g","47.5 grams"]].map(([id,label])=><Link key={id} href={`/product/${id}`} className={product.id===id?c.selectedSize:""}>{label}</Link>)}</div></div>}
 <div className={c.promoImages}><ProductArt src="/product/cashback.webp" alt="Welcome to Barwaqt — cashback promotion"/><ProductArt src="/product/grocery-banner.webp" alt="Discover fresh grocery favourites"/></div>

 </section><aside className={c.sellerColumn}><div className={c.sellerBox}><div className={c.purchasePrice}><small>Product price</small><strong>AED {formatMoney(product.price)}</strong></div><div className={c.deliveryCard}><b>⌖ DELIVERY OPTIONS</b><p>Select your address at checkout</p><span>Choose home or work delivery</span></div><div className={c.sellerTitle}><span>ن</span><div>Sold by <b>Barwaqt {coffee?"Grocery":"Store"}</b><p className={c.green}>★ 3.7 <span className={c.muted}>75% Positive</span></p></div></div><div className={c.sellerStat}>Item as shown <b>90%</b></div><div className={c.sellerStat}>Partner since <b>1+ year</b></div><div className={c.trust}><p>◷ {coffee?"This item is not eligible for return":"Returns subject to seller policy"}</p><p>♧ Secure shopping</p></div><div className={c.quantityLabel}><b>Quantity</b><div className={c.quantityStepper}><button aria-label="Decrease quantity" disabled={quantity<=1} onClick={()=>setQuantity(q=>Math.max(1,q-1))}>−</button><output aria-label="Selected quantity">{quantity}</output><button aria-label="Increase quantity" disabled={quantity>=99} onClick={()=>setQuantity(q=>Math.min(99,q+1))}>+</button></div></div><button className={c.blueButton} onClick={()=>add()}>ADD TO CART</button><button className={c.buyNow} onClick={buyNow}>ϟ BUY NOW</button><Link className={c.viewCartLink} href="/checkout">View cart ({count}) →</Link></div><div className={c.sellerAd}><p>Your everyday choice!</p><Link href="/product/klassno-coffee-mix"><ProductArt src="/product/coffee-mix.webp" alt="Klassno instant coffee"/><div>Klassno Coffee Mix 3 in 1<strong>AED 12.40</strong><span className={c.express}>express</span></div></Link></div></aside></div>
 <section className={c.bundleSection}><p className={c.eyebrow}>FREQUENTLY BOUGHT TOGETHER</p><div className={c.bundle}>{bundleProducts.map(p=><label key={p.id}><input type="checkbox" checked={bundle.includes(p.id)} onChange={e=>setBundle(previous=>e.target.checked?[...previous,p.id]:previous.filter(id=>id!==p.id))}/><ProductArt src={p.image} alt={p.name}/><b>AED {formatMoney(p.price*(p.id===product.id?quantity:1))}</b><p>{p.name}</p></label>)}</div><button className={c.outlineButton} disabled={!bundle.length} onClick={()=>add(bundle)}>BUY {bundle.length} TOGETHER FOR AED {formatMoney(bundleProducts.reduce((sum,p)=>sum+(bundle.includes(p.id)?p.price*(p.id===product.id?quantity:1):0),0))}</button></section><ProductSections key={product.id} product={product}/><section className={c.related}><h2>You may also like</h2><Recommendations products={related}/></section></main><ShopFooter/>
 <dialog ref={zoom} className={c.imageZoom} aria-label="Product image preview"><button aria-label="Close image preview" onClick={()=>zoom.current?.close()}>×</button><ProductArt src={gallery[imageIndex]} alt={product.name}/></dialog>
 <dialog aria-label="Added to cart" ref={drawer} className={c.drawer} onClick={e=>{if(e.target===e.currentTarget)drawer.current?.close();}}><div className={c.dialogHeader}><h2>✓ Added to cart</h2><button aria-label="Close cart drawer" onClick={()=>drawer.current?.close()}>×</button></div><div className={c.addedProduct}><ProductArt src={product.image} alt={product.name}/><div><h3>{product.name}</h3><p>AED {formatMoney(product.price)}</p></div></div><h3>Complete your basket</h3><Recommendations products={related.slice(0,3)}/><div className={c.drawerActions}><Link href="/checkout" onNavigate={() => drawer.current?.close()} className={c.blueButton}>VIEW CART ({count})</Link><button className={c.outlineButton} onClick={()=>drawer.current?.close()}>CONTINUE SHOPPING</button></div></dialog></>;
}
