"use client";
import { useState } from "react";
import data from "../shop-data.json";
import s from "./product-sections.module.css";
type Product=typeof data.products[number];
type Review={name:string;rating:number;title:string;body:string};
export default function ProductSections({product}:{product:Product}){
 const [writing,setWriting]=useState(false);const [reviews,setReviews]=useState<Review[]>([]);const [draft,setDraft]=useState<Review>({name:"",rating:5,title:"",body:""});const [rating,setRating]=useState(0);const [query,setQuery]=useState("");const [helpful,setHelpful]=useState<number[]>([]);
 const faqs=[['How do I choose a product option?','Available options are shown above the purchase controls. Check the product name and selected option before adding it to your cart.'],['How can I check delivery options?','Add the item to your cart and continue to checkout. Select an address and delivery preference. This storefront currently demonstrates the checkout flow.'],['Can I save this product for later?','Use the heart beside the product image. Your saved items are available on the Wishlist page in this browser.'],['How do I use a coupon?','Copy WELCOME10 from the price panel and apply it in the cart. It gives 10% off items, up to AED 50 in this demo.'],['Where can I find warranty and return details?','Warranty and return terms vary by product and seller. Confirm the applicable policy before making a real purchase; this demo does not process real orders.']];
 const visible=reviews.filter(r=>!rating||r.rating===rating);const questions=faqs.filter(([q,a])=>(q+' '+a).toLowerCase().includes(query.toLowerCase()));
 return <><section className={s.section} id="product-specifications"><header><div><h2>Product specifications</h2><p>Details for your selected product</p></div></header><div className={s.specs}><dl>{[['Product name',product.name],['Product code',product.id],['Collection',product.section],['Current price',`AED ${product.price.toFixed(2)}`],['Selected size',product.id==='nescafe-gold-190g'?'190 grams':product.id==='nescafe-gold-47g'?'47.5 grams':'Standard selection']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><aside><h3>Your selected item</h3><p>{product.name}</p><ul><li>Check the selected option before checkout.</li><li>Delivery preferences are selected during checkout.</li><li>Product images remain the original catalog images.</li></ul><div className={s.note}>Demo catalog: additional manufacturer specifications and package contents have not been supplied.</div></aside></div></section>
 <section className={s.section} id="product-reviews"><header><div><h2>Customer reviews</h2><p>Try the review interface with feedback saved for this page session.</p></div><button className={s.primary} onClick={()=>setWriting(!writing)}>{writing?'Cancel review':'✎ Write a review'}</button></header><div className={s.reviewSummary}><div className={s.score}><strong>{product.rating.toFixed(1)}</strong><span>★★★★★</span><p>Catalog reference rating</p></div><div><h3>Your experience matters</h3><p>Share what you think about the product. Reviews submitted here are local demo feedback, not verified customer purchases.</p><b>{reviews.length} demo {reviews.length===1?'review':'reviews'} this session</b></div></div>{writing&&<form className={s.form} onSubmit={e=>{e.preventDefault();if(!draft.name.trim()||!draft.title.trim()||!draft.body.trim())return;setReviews(previous=>[...previous,{...draft,name:draft.name.trim(),title:draft.title.trim(),body:draft.body.trim()}]);setDraft({name:'',rating:5,title:'',body:''});setWriting(false);setRating(0);}}><div><label>Your name<input required maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Rating<select value={draft.rating} onChange={e=>setDraft({...draft,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label></div><label>Review title<input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Your review<textarea required maxLength={2000} rows={4} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><button className={s.primary}>SUBMIT DEMO REVIEW</button></form>}<div className={s.filters}><b>FILTER BY:</b>{[0,5,4,3,2,1].map(n=><button key={n} aria-pressed={rating===n} onClick={()=>setRating(n)}>{n?`${n} stars`:`All reviews (${reviews.length})`}</button>)}</div>{visible.length?visible.map(r=>{const index=reviews.indexOf(r);return <article key={index} className={s.review}><div><strong>{r.name}</strong><span>Demo review · This session</span></div><h3><span>{'★'.repeat(r.rating)}</span> {r.title}</h3><p>{r.body}</p><footer><small>{product.name}</small><button aria-pressed={helpful.includes(index)} onClick={()=>setHelpful(previous=>previous.includes(index)?previous.filter(i=>i!==index):[...previous,index])}>♡ Helpful ({helpful.includes(index)?1:0})</button></footer></article>}):<p className={s.empty}>{reviews.length?'No reviews match this rating.':'No customer reviews are available yet. Be the first to try a demo review.'}</p>}</section>
 <section className={s.section}><header><div><h2>Questions & answers</h2><p>Helpful information before you add to cart</p></div></header><input className={s.search} type="search" aria-label="Search product questions" placeholder="Search questions about delivery, options or coupons…" value={query} onChange={e=>setQuery(e.target.value)}/>{questions.map(([q,a])=><details className={s.question} key={q}><summary>{q}</summary><p>{a}</p></details>)}{!questions.length&&<p className={s.empty}>No matching questions. Try “delivery” or “coupon”.</p>}</section></>;
}
